# Generated by Django 2.2.2 on 2019-07-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('high', 'high'), ('low', 'low')], default='low', max_length=4),
        ),
    ]
